blank_issues_enabled: true
contact_links:
  - name: Project Discussions
    url: https://github.com/retrospct/hunter/discussions
    about: Please ask and answer questions here.
  - name: Project Security Policy
    url: https://github.com/retrospct/hunter/security/policy
    about: Please report security vulnerabilities here.
