blank_issues_enabled: true
contact_links:
  - name: Project Discussions
    url: https://github.com/<YOUR_GITHUB_USERNAME_OR_ORG>/multi-company-job-monitor/discussions
    about: Please ask and answer questions here.
  - name: Project Security Policy
    url: https://github.com/<YOUR_GITHUB_USERNAME_OR_ORG>/multi-company-job-monitor/security/policy
    about: Please report security vulnerabilities here.
